spring:
  application:
    name: DiscountCodesManager

  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/master.xml